#!/bin/bash
#
# /etc/init.d/xvfbdm-twm
#
# chkconfig:  345 97 27
# description: Starts/Stops twm for the X Virtual Framebuffer server

### BEGIN INIT INFO
# Provides:          xvfbdm-twm
# Should-Start:      
# Required-Start:    $local_fs $remote_fs xvfbdm
# Required-Stop:     $local_fs $remote_fs
# Default-Start:     3 4 5
# Default-Stop:      0 1 2 6
# Short-Description: Window Manager for Xvfbdm 
# Description:       Init script for TWM to support pdf printing on Oracle with Xvfb
### END INIT INFO
#
# Author:       Greg Dahlman <gdahlm@hotmail.com>
#

. /etc/init.d/functions

PROG="/usr/bin/twm"
PROG_OPTIONS="-display :5"
PROG_OUTPUT="/tmp/twm.out"

case "$1" in
    start)
        echo "Starting : X Virtual Frame Buffer Window Manager"
        $PROG $PROG_OPTIONS>>$PROG_OUTPUT 2>&1 &
        disown -ar
        /bin/usleep 500000
        status twm & >/dev/null && echo_success || echo_failure
        RETVAL=$?
        if [ $RETVAL -eq 0 ]; then
            /bin/touch /var/lock/subsys/twm
            /sbin/pidof -o  %PPID -x twm > /var/run/twm.pid
        fi
        echo
                ;;
    stop)
        echo "Shutting down : X Virtual Frame Buffer"
        killproc $PROG
        RETVAL=$?
        [ $RETVAL -eq 0 ] && /bin/rm -f /var/lock/subsys/twm /var/run/twm.pid
        echo
        ;;
    restart|reload)
        $0 stop
        $0 start
        RETVAL=$?
        ;;
    status)
        status twm
        RETVAL=$?
        ;;
    *)
     echo $"Usage: $0 (start|stop|restart|status)"
     exit 1
esac
exit $RETVAL

